"""
https://projecteuler.net/problem=2
Each new term in the Fibonacci sequence is generated by adding the previous two terms.
By starting with 1 1 2 3 5 8
By considering the terms in the Fibonacci sequence whose values do not exceed four million,
find the sum of the even-valued terms.
"""

prev, cur = 0, 1
total = 0
max_v = 4 * 10 ** 6
while True:
    prev, cur = cur, prev + cur
    if cur >= max_v:
        break
    if cur % 2 == 0:
        total += cur
print(total)
