"""
https://projecteuler.net/problem=2
Each new term in the Fibonacci sequence is generated by adding the previous two terms.
By starting with 1 1 2 3 5 8
By considering the terms in the Fibonacci sequence whose values do not exceed four million,
find the sum of the even-valued terms.
"""

from tools.Fibonacci import gen_fibonacci

s = 0
max_v = 4 * 10 ** 6
for f in gen_fibonacci():
	if f < max_v:
		if f % 2 == 0:
			s += f
	else:
		print(s)
		break
